"""Structured reporting primitives and presentation models."""

from wysteria.reporting.builder import (
    build_developer_report,
    build_report,
    categorize_diagnostic_code,
    diagnostic_sort_key,
    extract_node_id,
    format_developer_report,
    format_policy_report,
    format_report_json,
    make_status_presentation,
    normalize_diagnostic,
)
from wysteria.reporting.diagnostics import (
    Diagnostic,
    Severity,
    SourceLocation,
    ValidationResult,
)
from wysteria.reporting.gate import evaluate_gate
from wysteria.reporting.github import (
    escape_github_data,
    escape_github_property,
    format_diagnostic_annotation,
    format_github_annotations,
)
from wysteria.reporting.models import (
    AssertionReportItem,
    BaselineDiffEntry,
    BaselineSummary,
    DeveloperReport,
    DiagnosticCategory,
    ExecutionSummary,
    FixtureIdentity,
    GateDecision,
    GateSummary,
    MatchState,
    NormalizedDiagnostic,
    OutputReportItem,
    ReportStatus,
    StatusBadge,
    StatusPresentation,
    ValidationSummary,
    WorkflowIdentity,
)

__all__ = [
    "AssertionReportItem",
    "BaselineDiffEntry",
    "BaselineSummary",
    "DeveloperReport",
    "Diagnostic",
    "DiagnosticCategory",
    "ExecutionSummary",
    "FixtureIdentity",
    "GateDecision",
    "GateSummary",
    "MatchState",
    "NormalizedDiagnostic",
    "OutputReportItem",
    "ReportStatus",
    "Severity",
    "SourceLocation",
    "StatusBadge",
    "StatusPresentation",
    "ValidationResult",
    "ValidationSummary",
    "WorkflowIdentity",
    "build_developer_report",
    "build_report",
    "categorize_diagnostic_code",
    "diagnostic_sort_key",
    "escape_github_data",
    "escape_github_property",
    "evaluate_gate",
    "extract_node_id",
    "format_developer_report",
    "format_diagnostic_annotation",
    "format_github_annotations",
    "format_policy_report",
    "format_report_json",
    "make_status_presentation",
    "normalize_diagnostic",
]
